// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using graduation_project.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace graduation_project.Data
{
    public partial interface IFashionDesignContextProcedures
    {
        Task<List<GetOfferForClientResult>> GetOfferForClientAsync(string Ur, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOfferForClientPagesResult>> GetOfferForClientPagesAsync(string Ur, int? page, int? items, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOfferForTailorResult>> GetOfferForTailorAsync(string ur, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOfferForTailorPagesResult>> GetOfferForTailorPagesAsync(string Ur, int? page, int? items, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
